name: snapapp
description: "A Test Flutter App - Build Snap with flutter_secure_storage."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
    # 20260310 gjw With flutter_secure_storage I have not been able to
    # build a snap package using canonical github work flow

  flutter_secure_storage: any
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
