name: Build Snap

on: push

env:
  APP: snapapp
  RELEASE: dev
  LINUX_PKGS: libsecret-1-dev libjsoncpp-dev
  FLUTTER_VERSION: "3.41.1"

jobs:

  package-linux-snap:

    runs-on: ubuntu-latest

    steps:

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install extra Linux packages
        if: env.LINUX_PKGS != ''
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y ${{env.LINUX_PKGS}}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: TEST Install Flutter Project Dependencies
        run: |
          flutter --version
          flutter clean
          flutter pub get
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Build snap
        uses: canonical/action-build@v1
        id: build

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP }}-linux-snap
          path: ${{ steps.build.outputs.snap }}
